### ISSUE TITLE
Could you kindly share the reference code of RNN-Nade?

### ISSUE THREAD

**Issue by byzhang** [boulanni/theano-hf#2]
It's still the state-of-the-art on multiple music datasets per http://arxiv.org/pdf/1312.6026.pdf.

**Comment by boulanni** [comment]
Here is my code for NADE: http://www-etud.iro.umontreal.ca/~boulanni/nade.py
You should be able to put the pieces together along with the RNN-RBM tutorial (http://deeplearning.net/tutorial/rnnrbm.html) and the HF code in this repository.

Let me know if you have more questions!
